### ISSUE TITLE
cannot execute on local

### ISSUE THREAD

**Issue by pp86** [DEIB-GECO/GMQL#31]
Looks like the conf/logback.xml is not there.
What shall I do?

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/pietro/.m2/repository/org/slf4j/slf4j-log4j12/1.7.16/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/pietro/.m2/repository/ch/qos/logback/logback-classic/1.2.2/logback-classic-1.2.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:ERROR Could not parse file [../conf/logback.xml].
java.io.FileNotFoundException: /Users/pietro/Desktop/gmql29/GMQL/../conf/logback.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:622)
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:189)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:812)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at org.apache.log4j.xml.DOMConfigurator$1.parse(DOMConfigurator.java:749)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:871)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:755)
	at org.apache.log4j.xml.DOMConfigurator.configure(DOMConfigurator.java:896)
	at it.polimi.genomics.cli.GMQLExecuteCommand$.<init>(GMQLExecuteCommand.scala:28)
	at it.polimi.genomics.cli.GMQLExecuteCommand$.<clinit>(GMQLExecuteCommand.scala)
	at it.polimi.genomics.cli.GMQLExecuteCommand.main(GMQLExecuteCommand.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
log4j:WARN No appenders could be found for logger (it.polimi.genomics.cli.GMQLExecuteCommand$).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Process finished with exit code 0

**Comment by akaitoua** [comment]
@pp86 would you try to comment these lines from CLI class


 try{
       DOMConfigurator.configure("../conf/logback.xml")
    val root:ch.qos.logback.classic.Logger = org.slf4j.LoggerFactory.getLogger("org").asInstanceOf[ch.qos.logback.classic.Logger];
    root.setLevel(ch.qos.logback.classic.Level.WARN);
   org.slf4j.LoggerFactory.getLogger("it.polimi.genomics.cli").asInstanceOf[ch.qos.logback.classic.Logger].setLevel(ch.qos.logback.classic.Level.INFO)
  }catch{
    case _:Throwable => logger.warn("log4j.xml is not found in conf")
  }

**Comment by pp86** [comment]
Ok, I tried but now it just to do nothing.

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:........./StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:........./StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:WARN No appenders could be found for logger (it.polimi.genomics.cli.GMQLExecuteCommand$).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by pp86** [comment]
I mean,
what I attached is all I get, it just return after printing those warnings

**Comment by akaitoua** [comment]
@pp86, you can try to add the dependancy of logback and log4j to the pom file of GMQL-Cli module.
