### ISSUE TITLE
Cannot execute CLI 

### ISSUE THREAD

**Issue by pp86** [DEIB-GECO/GMQL#94]
I cloned the GIT (latest commit: 884323724cbbcebdbcc2a554cab1f47880a4f663), changed in the main class the spark master to be `local[*]` and packaged with maven. Compilation succeeded, but when I try to run it I get:

`java.lang.NoSuchMethodError: com.google.common.base.Stopwatch.elapsedMillis()J
	at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.listStatus(FileInputFormat.java:279)
	at org.apache.hadoop.mapreduce.lib.input.CombineFileInputFormat.getSplits(CombineFileInputFormat.java:217)
	at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:125)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.Partitioner$$anonfun$defaultPartitioner$2.apply(Partitioner.scala:66)
	at org.apache.spark.Partitioner$$anonfun$defaultPartitioner$2.apply(Partitioner.scala:66)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at org.apache.spark.Partitioner$.defaultPartitioner(Partitioner.scala:66)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$cogroup$5.apply(PairRDDFunctions.scala:846)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$cogroup$5.apply(PairRDDFunctions.scala:846)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.PairRDDFunctions.cogroup(PairRDDFunctions.scala:845)
	at it.polimi.genomics.spark.implementation.MetaOperators.SelectMeta.MetaSelection$class.applyMetaSelect(MetaSelection.scala:42)
	at it.polimi.genomics.spark.implementation.MetaOperators.SelectMeta.SelectMD$metaSelection$.applyMetaSelect(SelectMD.scala:26)
	at it.polimi.genomics.spark.implementation.MetaOperators.SelectMeta.SelectIMDWithNoIndex$.apply(SelectIMDWithNoIndex.scala:82)
	at it.polimi.genomics.spark.implementation.GMQLSparkExecutor.implement_md(GMQLSparkExecutor.scala:200)
	at it.polimi.genomics.spark.implementation.MetaOperators.SelectMeta.StoreMD$.apply(StoreMD.scala:21)
	at it.polimi.genomics.spark.implementation.GMQLSparkExecutor.implement_md(GMQLSparkExecutor.scala:195)
	at it.polimi.genomics.spark.implementation.GMQLSparkExecutor$$anonfun$implementation$1.apply(GMQLSparkExecutor.scala:114)
	at it.polimi.genomics.spark.implementation.GMQLSparkExecutor$$anonfun$implementation$1.apply(GMQLSparkExecutor.scala:112)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:73)
	at scala.collection.mutable.MutableList.foreach(MutableList.scala:30)
	at it.polimi.genomics.spark.implementation.GMQLSparkExecutor.implementation(GMQLSparkExecutor.scala:112)
	at it.polimi.genomics.spark.implementation.GMQLSparkExecutor.go(GMQLSparkExecutor.scala:59)
	at it.polimi.genomics.GMQLServer.GmqlServer.run(GmqlServer.scala:23)
	at it.polimi.genomics.cli.GMQLExecuteCommand$.main(GMQLExecuteCommand.scala:261)
	at it.polimi.genomics.cli.GMQLExecuteCommand.main(GMQLExecuteCommand.scala)`

**Comment by pp86** [comment]
Solved; now GMQL-Cli is packaged as uber-jar.

Thanks @lucananni93
